In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1) # num_features and output
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [2]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features) they use @magic_function
model(features)

tensor([[0.6053],
        [0.5814],
        [0.5938],
        [0.5718],
        [0.5396],
        [0.6213],
        [0.5930],
        [0.5698],
        [0.6178],
        [0.6030]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0112,  0.2423, -0.3733,  0.0984,  0.1231]], requires_grad=True)

In [4]:
from torchinfo import summary

summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Let's Create a Neural Network with more then 1 hidden layers.

In [5]:
# create model class
import torch
import torch.nn as nn

class Model1(nn.Module):

  def __init__(self, num_features): # Initialization of the Neural Network

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3) # num_features and output
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features): # Forward Propagation

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [6]:
# create dataset
features = torch.rand(10, 5)

# create model
model1 = Model1(features.shape[1])

# call model for forward pass
# model.forward(features)@magic_function
model1(features)

tensor([[0.5161],
        [0.5233],
        [0.5428],
        [0.5234],
        [0.5208],
        [0.5373],
        [0.5387],
        [0.5018],
        [0.5228],
        [0.5365]], grad_fn=<SigmoidBackward0>)

In [7]:
# show model weights
model1.linear1.weight

Parameter containing:
tensor([[ 0.4273, -0.3936, -0.3399, -0.2703, -0.1064],
        [-0.1514, -0.2603,  0.0408,  0.3144,  0.4208],
        [ 0.1734, -0.1576,  0.4308, -0.3403, -0.4435]], requires_grad=True)

In [8]:
# show model weights
model1.linear2.weight

Parameter containing:
tensor([[-0.5042,  0.2480, -0.1763]], requires_grad=True)

In [9]:
from torchinfo import summary

summary(model1, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Sequential Container in PyTorch

In [10]:
# create model class
import torch
import torch.nn as nn

class Model2(nn.Module):

  def __init__(self, num_features): # Initialization of the Neural Network

    super().__init__()
    self.network = nn.Sequential(
                                nn.Linear(num_features, 3), # num_features and output
                                nn.ReLU(),
                                nn.Linear(3, 1),
                                nn.Sigmoid())

  def forward(self, features): # Forward Propagation

    out = self.network(features)

    return out

In [11]:
# create dataset
features = torch.rand(10, 5)

# create model
model2 = Model2(features.shape[1])

# call model for forward pass
# model.forward(features)@magic_function
model2(features)

tensor([[0.4352],
        [0.4710],
        [0.4624],
        [0.4549],
        [0.4629],
        [0.4671],
        [0.4695],
        [0.4605],
        [0.4360],
        [0.4534]], grad_fn=<SigmoidBackward0>)